import { NextResponse } from "next/server";
import { prisma } from "@/src/lib/prisma";
import { getSessionUser } from "@/src/lib/session";

export async function GET(
  _req: Request,
  ctx: { params: Promise<{ code: string }> },
) {
  const { code } = await ctx.params;
  const user = await getSessionUser();
  if (!user) return new NextResponse("Unauthorized", { status: 401 });

  const room = await prisma.room.findUnique({
    where: { code: code.trim().toUpperCase() },
    include: {
      admin: { select: { username: true } },
      memberships: { include: { user: { select: { username: true } } } },
    },
  });
  if (!room) return new NextResponse("Not found", { status: 404 });

  const isMember = room.memberships.some((m) => m.userId === user.id);
  if (!isMember) return new NextResponse("Forbidden", { status: 403 });

  const closedAt = room.closedAt ?? new Date();
  const durationMin = Math.max(
    1,
    Math.round((closedAt.getTime() - room.createdAt.getTime()) / 60000),
  );

  const header = [
    `# ${room.agendaTitle}`,
    "",
    `**Room:** ${room.code}`,
    `**Facilitator:** ${room.admin.username}`,
    `**Participants:** ${room.memberships.map((m) => m.user.username).join(", ")}`,
    `**Duration:** ${durationMin}m`,
    `**Outcome:** ${room.consensus === "REACHED" ? "Consensus reached" : "Closed before consensus"}`,
    "",
    "---",
    "",
  ].join("\n");

  const body = room.finalSummary ?? "(no summary was produced)";
  const footer = `\n\n---\n*Minutes generated by Consensus · ${closedAt.toISOString()}*\n`;

  return new NextResponse(header + body + footer, {
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Content-Disposition": `attachment; filename="consensus-${room.code}-minutes.md"`,
    },
  });
}
